import { Phone, ShieldCheck, Mic2, UserRound, FileText, ArrowRight, Gavel, Scale, CarFront, Building2, Send } from 'lucide-react'
const number=import.meta.env.VITE_CALL_CENTER_NUMBER||''
const ROUTES=[{title:'Sud',icon:Gavel,text:'Sudga oid masalalar',tone:'gold'},{title:'Prokuratura',icon:Scale,text:'Qonuniylik va murojaatlar',tone:'red'},{title:'IIV',icon:ShieldCheck,text:'Ichki ishlar va xavfsizlik',tone:'blue'},{title:'DXX',icon:ShieldCheck,text:'Davlat xavfsizligi yo‘nalishi',tone:'violet'},{title:'YPX',icon:CarFront,text:'Yo‘l harakati masalalari',tone:'amber'}]
const tones={gold:'text-amber-200 bg-amber-300/10',red:'text-red-200 bg-red-400/10',blue:'text-sky-200 bg-sky-400/10',violet:'text-violet-200 bg-violet-400/10',amber:'text-orange-200 bg-orange-400/10'}
export default function CallCenter(){
 const choose=()=>document.getElementById('institutions')?.scrollIntoView({behavior:'smooth'})
 return <section id="call-center" className="relative mx-auto max-w-7xl px-6 py-24"><div className="call-center-shell overflow-hidden rounded-[32px] border border-emerald-300/10 bg-[#061019]/90 p-6 shadow-[0_40px_120px_rgba(0,0,0,.45)] backdrop-blur-2xl sm:p-10"><div className="absolute pointer-events-none -right-20 -top-20 h-72 w-72 rounded-full bg-emerald-300/10 blur-[100px]"/><div className="relative grid gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center">
  <div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs font-medium text-emerald-200"><Phone className="h-3.5 w-3.5"/> MADADKOR CALL-CENTER</div><h2 className="text-3xl font-black tracking-tight text-white sm:text-5xl">Muammoni ayting. <span className="text-gradient">Qaysi yo‘l kerakligini topamiz.</span></h2><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base">Muammoingizni ayting, Madadkor huquqiy yo‘nalishni tushuntiradi. Zarur bo‘lsa, tegishli tashkilotga murojaat qilish yoki call-center orqali yordam olish yo‘lini ko‘rsatadi.</p>
   <div className="mt-7 grid gap-3 sm:grid-cols-3">{[['1','Muammo','Vaziyatni oddiy tilda ayting'],['2','Yo‘nalish','Qaysi idoraga tegishli ekanini ko‘ring'],['3','Murojaat','Call-center yoki rasmiy xizmatga o‘ting']].map(([n,title,text])=><div key={n} className="workflow-card"><span className="workflow-num">0{n}</span><div><h3 className="text-sm font-semibold text-white">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-400">{text}</p></div></div>)}</div>
   <div className="mt-8 grid gap-3 sm:grid-cols-2">{ROUTES.map(({title,icon:Icon,text,tone})=><button key={title} onClick={choose} className="group flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.025] p-3 text-left transition hover:-translate-y-0.5 hover:border-emerald-300/20 hover:bg-white/[0.05]"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${tones[tone]}`}><Icon className="h-5 w-5"/></span><span className="min-w-0"><span className="block text-sm font-bold text-white">{title}</span><span className="block text-xs text-slate-500">{text}</span></span><ArrowRight className="ml-auto h-4 w-4 text-slate-600 transition group-hover:translate-x-1 group-hover:text-emerald-300"/></button>)}</div>
  </div>
  <div className="call-terminal rounded-[28px] border border-white/10 bg-black/25 p-6"><div className="flex items-center gap-3"><div className="relative flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-400/10 text-emerald-300"><span className="absolute inset-0 rounded-2xl border border-emerald-300/20 animate-pulse"/><Mic2 className="relative h-6 w-6"/></div><div><p className="text-xs text-slate-400">Madadkor Call-center</p><p className="text-lg font-bold text-white">{number||'Raqam ulanmoqda'}</p></div></div><div className="mt-6 space-y-3 text-sm text-slate-300"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-300"/><span>O‘zbekcha, ravon va hurmatli suhbat</span></div><div className="flex gap-3"><UserRound className="h-5 w-5 shrink-0 text-violet-300"/><span>Zarur bo‘lsa inson yuristga yo‘naltirish</span></div><div className="flex gap-3"><FileText className="h-5 w-5 shrink-0 text-sky-300"/><span>Suhbatdan keyin CASE va xulosa yaratish</span></div><div className="flex gap-3"><Building2 className="h-5 w-5 shrink-0 text-amber-200"/><span>Muammoga mos tashkilot yo‘nalishini tanlash</span></div></div>{number?<a href={`tel:${number}`} className="mt-7 flex items-center justify-center gap-2 rounded-2xl bg-emerald-400 px-5 py-3 text-sm font-bold text-slate-950 transition hover:brightness-110"><Phone className="h-4 w-4"/> Qo‘ng‘iroq qilish <ArrowRight className="h-4 w-4"/></a>:<div className="mt-7 rounded-2xl border border-amber-400/20 bg-amber-400/10 p-4 text-xs leading-6 text-amber-100">Call-center raqami hali ulanmagan. Rasmiy raqam tasdiqlangach, shu yerga ulab qo‘yish mumkin.</div>}<button onClick={()=>window.dispatchEvent(new CustomEvent('madadkor:start-call',{detail:{message:'Menga huquqiy murojaat tayyorlashda yordam bering.'}}))} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/[0.04] px-5 py-3 text-sm font-bold text-white hover:bg-white/[0.07]"><Send className="h-4 w-4"/> Murojaatni boshlash</button></div>
 </div></div></section>
}
